name: gen
description: 'A new Flutter package project.'
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  envied: ^0.5.4+1
  lottie: ^3.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true

  assets:
    enabled: true

    outputs:
      package_parameter_enabled: true
      class_name: ProjectAssets

  colors:
    inputs:
      - assets/color/color.xml

flutter:
  assets:
    - assets/color/
    - assets/lottie/
    - assets/icons/
    - assets/images/
