name: teamup
description: 'A new Flutter project.'

publish_to: 'none'
version: 1.1.1+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.5
  easy_localization: ^3.0.7

  gen:
    path: module/gen

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
